[phases.setup]
nixPkgs = ['mdbook', 'cargo', 'gcc', 'python3']

[phases.install]
cmds = [
  'cargo install mdbook-i18n --locked',
  'echo "Skipping npm install"'
]

[phases.build]
cmds = ['export PATH="/root/.cargo/bin:$PATH" && mdbook build']

[start]
cmd = 'cd book && python3 -m http.server 3000'