[phases.setup]
nixPkgs = ['mdbook', 'mdbook-i18n']

[phases.install]
cmds = ['echo "Skipping npm install"']

[phases.build]
cmds = ['mdbook build']

[start]
cmd = 'mdbook serve --hostname 0.0.0.0 --port 3000'
